### PR TITLE
fix(github_action/pythonpackage): separate run test into 3 steps

### PR DESCRIPTION
**Pull request by Lee-W**
This PR is based #100 and should be reviewed after #100 is merged.
There is an error hard to fix in the original design but is fixed in the "refactor-config" new design.

without separating, the pipeline will continue when the third step succeeded even if the first two steps failed

#106

### CODE REVIEW

**Comment by Lee-W** [comment]
@Woile I've tested the failed test `test_bump_command` on my local machine, but it succeeded. Do you have any clue on why this failed in Github Action?

**Comment by Lee-W** [comment]
I've already figured out the problem is lacking git user when running test and fixed it.

**Comment by Woile** [comment]
I would like to leave the `./scripts/test`. I want to keep the same interface for local development and ci.
If you check `.github/workflows/bumpversion.yml`, there's a `Configure repo` step, we can try adding that. But I've seen it failed when any of the steps fail. Could you share which step failed? Keep in mind that github actions are quite new and they are not working 100% fine.

**Comment by Lee-W** [comment]
The configure is not the main problem. The problem is that the script will go on even if the previous steps fail. For example, if I send a pull request that cannot pass the unit tests but without any style error. The pipeline will succeed. I would recommend using `invoke` or `make` to solve this problem. I just tested if any of the steps return status code other than 0, both tool will break immediately.

**Comment by Woile** [comment]
We only need to add `#!/bin/sh -e` at the beginning of the script and it will be solved.

> -e | If non-interactive, exit immediately if a command fails.

**Comment by Lee-W** [comment]
That sounds great. I just send another PR https://github.com/Woile/commitizen/pull/109 for it. I'll close this one.

**Pull request closed without merging**
