### PR TITLE
Enhance customization

### PR DESCRIPTION
**Pull request by Lee-W**
* add utils
  * required_validator
  * multiple_line_breaker
* add jinja support for cz_customization

#6 , #24 , #54

### CODE REVIEW

**Comment by Woile** [comment]
Hey Lee please rebase and remove the extra commit. 

```bash
git rebase -i origin/master
```
and add the option `drop` into the extra commit. Then continue normally the rebase.

**Comment by Woile** [comment]
I prefer not introducing dependencies like `jinja`. For me it's more than enough with `from string import Template`. I'd be willing to add jinja as an extra dependency.
In order to do so, you can install it doing `poetry add jinja2 --optional`
And then in the code:

```
try:
    from jinja2 import Template
except ImportError
    from string import Template
```
I think the interface of both templates is slightly different so it should be adjusted.

**Comment by Lee-W** [comment]
Yes, that makes sense to me. I've updated it.

**Comment by Lee-W** [comment]
Should we close #6 , #24 , #54? Or, is there any other we should do on those issues?

**Pull request merged**
